### ISSUE TITLE
Does gltext work with gomobile for native Android app?

### ISSUE THREAD

**Issue by udhos** [4ydx/gltext#1]
Can this package be used with gomobile to build a native Android app?

**Comment by 4ydx** [comment]
In order to try this out you would need to determine which version of opengl you need to support.  This package currently uses opengl 4.1 from https://github.com/go-gl/gl.

If you are using golang.org/x/mobile/gl, then you can try replacing the imports, altering any required api calls, and just give it a try.  I don't believe I am doing anything too crazy in the shaders.  

If you give me more details about your build process (tools, environment etc) and provide me with very basic starting code, I would be happy to try it myself when I have some free time.

**Comment by udhos** [comment]
If you think you could give a try on gomobile:

I have a little experiment on gomobile here: https://github.com/udhos/fugo
Full build instructions are available in the README.md.
Rendering is on method paint(): https://github.com/udhos/fugo/blob/master/demo/invader/paint.go

If you need any further directions, I can help.

**Comment by 4ydx** [comment]
Will take a look.

**Comment by 4ydx** [comment]
I haven't had time to look at this so I am closing for now.
